# Generated by Django 5.1.2 on 2025-01-17 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Material Name')),
            ],
        ),
        migrations.CreateModel(
            name='TechSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Technical Specification Name')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the store.', max_length=255, unique=True)),
                ('location', models.CharField(blank=True, help_text='Location or address of the store.', max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for the store.', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number for the store.', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the store was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the store was last updated.')),
                ('managers', models.ManyToManyField(blank=True, help_text='Users associated with this store.', related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('specification_sheet', models.FileField(blank=True, null=True, upload_to='spec_sheets/')),
                ('tech_spec_01_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Technical Specification Value 1')),
                ('tech_spec_02_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Technical Specification Value 2')),
                ('tech_spec_03_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Technical Specification Value 3')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.material', verbose_name='Material')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.subcategory')),
                ('tech_spec_01', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_1', to='inventory.techspec', verbose_name='Technical Specification 01')),
                ('tech_spec_02', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_2', to='inventory.techspec', verbose_name='Technical Specification 02')),
                ('tech_spec_03', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_3', to='inventory.techspec', verbose_name='Technical Specification 03')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.unitofmeasurement')),
            ],
        ),
    ]
