# Generated by Django 5.1.2 on 2025-01-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techspec',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Symbol'),
        ),
    ]
