# Generated by Django 5.1.2 on 2025-01-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplydemand_supplydemanditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplydemand',
            old_name='user',
            new_name='demander',
        ),
    ]
