# Generated by Django 5.1.2 on 2025-01-24 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_user_supplydemand_demander'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplydemand',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date of the supply demand.', null=True),
        ),
        migrations.AddField(
            model_name='supplydemand',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), help_text='Time of the supply demand.', null=True),
        ),
    ]
