# Generated by Django 5.1.2 on 2025-01-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplydemandreview_supplydemandreviewitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplydemandreviewitem',
            name='designation',
        ),
    ]
