# Generated by Django 5.1.2 on 2025-01-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_supplydemandreviewitem_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplydemandreviewitem',
            name='requested_quantity',
        ),
    ]
