# Generated by Django 5.1.2 on 2025-01-24 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_supplydemandreviewitem_requested_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the order was created.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='The status of the supply order.', max_length=50)),
                ('ordered_by', models.ForeignKey(help_text='The user who placed this supply order.', on_delete=django.db.models.deletion.CASCADE, related_name='ordered_supply_orders', to=settings.AUTH_USER_MODEL)),
                ('supply_demand_review', models.OneToOneField(help_text='The Supply Demand Review that generated this order.', on_delete=django.db.models.deletion.CASCADE, related_name='supply_order', to='inventory.supplydemandreview')),
            ],
            options={
                'verbose_name': 'Supply Order',
                'verbose_name_plural': 'Supply Orders',
                'ordering': ['-created_at'],
                'permissions': [('view_own_orders', 'Can view own orders'), ('view_orders_related_to_its_own_reviews', 'can view orders related to its own reviews')],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(help_text='Quantity of the product available in stock.')),
                ('ordered_quantity', models.PositiveIntegerField(default=0, help_text='Quantity of the product ordered.')),
                ('designation', models.CharField(help_text='Description of the product in case it is not in the product model.', max_length=255)),
                ('product', models.ForeignKey(blank=True, help_text='The product for this item. Can be null if the product does not exist.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('supply_order', models.ForeignKey(help_text='The supply order to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplyorder')),
            ],
            options={
                'verbose_name': 'Supply Order Item',
                'verbose_name_plural': 'Supply Order Items',
            },
        ),
    ]
