# Generated by Django 5.1.2 on 2025-01-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_supplyorder_supplyorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplydemandreview',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplydemandreview',
            name='time',
            field=models.TimeField(),
        ),
    ]
