# Generated by Django 5.1.2 on 2025-01-25 00:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_supplyorder_date_supplyorder_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the purchase demand was created.')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of the purchase demand.')),
                ('time', models.TimeField(default=datetime.time(0, 0), help_text='Time of the purchase demand.')),
                ('demander', models.ForeignKey(help_text='User who created the purchase demand.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Demand',
                'verbose_name_plural': 'Purchase Demands',
                'ordering': ['-created_at'],
                'permissions': [('view_own_purchasedemand', 'Can view own purchase demands')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product requested.')),
                ('designation', models.CharField(help_text='Description of the product in case it is not in the product model.', max_length=255)),
                ('purchase_demand', models.ForeignKey(help_text='Related purchase demand.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchasedemand')),
            ],
            options={
                'verbose_name': 'Purchase Demand Item',
                'verbose_name_plural': 'Purchase Demand Items',
            },
        ),
    ]
