# Generated by Django 5.1.2 on 2025-01-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_purchasedemand_purchasedemanditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registre_de_commerce', models.CharField(max_length=100, verbose_name='Registre de Commerce')),
                ('nis', models.CharField(max_length=50, verbose_name='NIS')),
                ('nif', models.CharField(max_length=50, verbose_name='NIF')),
                ('ai', models.CharField(max_length=50, verbose_name='AI')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
