# Generated by Django 5.1.2 on 2025-01-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purchase_demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bon_de_commande', to='inventory.purchasedemand')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_de_commandes', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Bon de Commande',
                'verbose_name_plural': 'Bons de Commande',
            },
        ),
        migrations.CreateModel(
            name='BonDeCommandeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.PositiveIntegerField(help_text='Quantity of the product ordered.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price of the product.', max_digits=10)),
                ('bon_de_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.bondecommande')),
                ('product', models.ForeignKey(blank=True, help_text='Product for the item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Bon de Commande Item',
                'verbose_name_plural': 'Bon de Commande Items',
            },
        ),
    ]
