# Generated by Django 5.1.2 on 2025-01-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_bondecommande_bondecommandeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the supplier.', max_length=255, null=True),
        ),
    ]
